/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Client {
  bootstrap(): Promise<void>
  createTopic(options: CreateTopicOptions): Promise<void>
  produce(options: ProduceOptions): Promise<string>
  poll(options: PollOptions): Promise<Array<DeliveredMessage>>
  subscribe(options: SubscribeOptions, onMessage: (msg: DeliveredMessage) => void | Promise<void>, onError?: (err: string) => void): Promise<Subscription>
  ack(lease: LeaseRef): Promise<void>
  nack(lease: LeaseRef): Promise<void>
  stats(): Promise<ClusterStats>
  close(): void
}

export declare class Subscription {
  unsubscribe(): void
}

export interface ClusterStats {
  lastApplied: string
  currentLeader: number
  currentTerm: string
  lastLogIndex: string
  isLeader: boolean
  topics: number
  messages: number
  inFlight: number
}

export declare function connect(nodes: Array<NodeAddr>, options?: ConnectOptions | undefined | null): Promise<Client>

export interface ConnectOptions {
  bootstrap?: boolean
}

export interface CreateTopicOptions {
  topic: string
  rateLimit?: RateLimit
  retention?: Retention
}

export interface DeliveredMessage {
  leaseId: string
  offset: string
  priority: number
  contentType: number
  payload: Buffer
  tsMs: string
}

export interface LeaseRef {
  topic: string
  group: string
  leaseId: string
}

export interface NodeAddr {
  id: number
  clientAddr: string
  peerAddr: string
}

export interface PollOptions {
  topic: string
  group: string
  max?: number
  visibilityMs?: number
  waitMs?: number
}

export interface ProduceOptions {
  topic: string
  body: Buffer
  priority?: number
}

export interface RateLimit {
  ratePerSec: number
  burst: number
}

export interface Retention {
  maxMessages: number
  maxAgeMs: number
}

export interface SubscribeOptions {
  topic: string
  group: string
  prefetch?: number
  visibilityMs?: number
  ackMode?: 'auto' | 'manual'
}
